// <auto-generated />
using System;
using FastServer.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FastServer.Infrastructure.Data.Migrations.PostgreSql
{
    [DbContext(typeof(PostgreSqlDbContext))]
    [Migration("20260128053854_CompleteInitialData")]
    partial class CompleteInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FastServer.Domain.Entities.LogMicroservice", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<DateTime?>("LogDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_log_date");

                    b.Property<string>("LogLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fastserver_log_level");

                    b.Property<string>("LogMicroserviceText")
                        .HasColumnType("text")
                        .HasColumnName("fastserver_logmicroservice_text");

                    b.HasKey("LogId");

                    b.HasIndex("LogId");

                    b.ToTable("FastServer_LogMicroservice", (string)null);

                    b.HasData(
                        new
                        {
                            LogId = 1L,
                            LogDate = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            LogLevel = "INFO",
                            LogMicroserviceText = "[AuthService] Inicio de autenticación para usuario: admin"
                        },
                        new
                        {
                            LogId = 2L,
                            LogDate = new DateTime(2025, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc),
                            LogLevel = "INFO",
                            LogMicroserviceText = "[ProductService] Búsqueda ejecutada: 'laptop gaming' - 15 resultados encontrados"
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogMicroserviceHistorico", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<DateTime?>("LogDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_log_date");

                    b.Property<string>("LogLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fastserver_log_level");

                    b.Property<string>("LogMicroserviceText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fastserver_logmicroservice_text");

                    b.HasKey("LogId");

                    b.HasIndex("LogId");

                    b.ToTable("FastServer_LogMicroservice_Historico", (string)null);

                    b.HasData(
                        new
                        {
                            LogId = 1L,
                            LogDate = new DateTime(2024, 12, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            LogLevel = "INFO",
                            LogMicroserviceText = "[AuthService] Autenticación histórica exitosa para usuario: admin"
                        },
                        new
                        {
                            LogId = 2L,
                            LogDate = new DateTime(2024, 12, 15, 10, 10, 0, 0, DateTimeKind.Utc),
                            LogLevel = "INFO",
                            LogMicroserviceText = "[ProductService] Búsqueda histórica ejecutada: 'gaming keyboard' - 12 resultados"
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogServicesContent", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<string>("LogServicesContentText")
                        .HasColumnType("text")
                        .HasColumnName("fastserver_logservices_content_text");

                    b.Property<string>("LogServicesDate")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fastserver_logservices_date");

                    b.Property<string>("LogServicesLogLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fastserver_logservices_log_level");

                    b.Property<string>("LogServicesState")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fastserver_logservices_state");

                    b.HasKey("LogId");

                    b.HasIndex("LogId");

                    b.ToTable("FastServer_LogServices_Content", (string)null);

                    b.HasData(
                        new
                        {
                            LogId = 1L,
                            LogServicesContentText = "{\"username\": \"admin\", \"timestamp\": \"2025-01-01T10:00:00Z\", \"ip\": \"192.168.1.100\"}",
                            LogServicesDate = "2025-01-01 10:00:00",
                            LogServicesLogLevel = "INFO",
                            LogServicesState = "SUCCESS"
                        },
                        new
                        {
                            LogId = 2L,
                            LogServicesContentText = "{\"searchTerm\": \"laptop gaming\", \"resultsCount\": 15, \"executionTime\": \"320ms\"}",
                            LogServicesDate = "2025-01-01 10:05:00",
                            LogServicesLogLevel = "INFO",
                            LogServicesState = "SUCCESS"
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogServicesContentHistorico", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<string>("LogServicesContentText")
                        .HasColumnType("text")
                        .HasColumnName("fastserver_logservices_content_text");

                    b.Property<string>("LogServicesDate")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fastserver_logservices_date");

                    b.Property<string>("LogServicesLogLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fastserver_logservices_log_level");

                    b.Property<string>("LogServicesState")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fastserver_logservices_state");

                    b.HasKey("LogId");

                    b.HasIndex("LogId");

                    b.ToTable("FastServer_LogServices_Content_Historico", (string)null);

                    b.HasData(
                        new
                        {
                            LogId = 1L,
                            LogServicesContentText = "{\"username\": \"admin\", \"timestamp\": \"2024-12-15T10:00:00Z\", \"ip\": \"192.168.1.50\", \"archived\": true}",
                            LogServicesDate = "2024-12-15 10:00:00",
                            LogServicesLogLevel = "INFO",
                            LogServicesState = "SUCCESS"
                        },
                        new
                        {
                            LogId = 2L,
                            LogServicesContentText = "{\"searchTerm\": \"gaming keyboard\", \"resultsCount\": 12, \"executionTime\": \"280ms\", \"archived\": true}",
                            LogServicesDate = "2024-12-15 10:10:00",
                            LogServicesLogLevel = "INFO",
                            LogServicesState = "SUCCESS"
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogServicesHeader", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fastserver_error_code");

                    b.Property<string>("ErrorDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("fastserver_error_description");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fastserver_http_method");

                    b.Property<string>("IpFs")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fastserver_ip_fs");

                    b.Property<DateTime>("LogDateIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_log_date_in");

                    b.Property<DateTime>("LogDateOut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_log_date_out");

                    b.Property<long?>("LogFsId")
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_fs_id");

                    b.Property<string>("LogMethodName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fastserver_log_method_name");

                    b.Property<string>("LogMethodUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fastserver_log_method_url");

                    b.Property<string>("LogNodo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fastserver_log_nodo");

                    b.Property<string>("LogState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fastserver_log_state");

                    b.Property<string>("MethodDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("fastserver_method_description");

                    b.Property<string>("MicroserviceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fastserver_microservice_name");

                    b.Property<long?>("RequestDuration")
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_request_duration");

                    b.Property<long?>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_request_id");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fastserver_session_id");

                    b.Property<string>("TciIpPort")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fastserver_tci_ip_port");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fastserver_transaction_id");

                    b.Property<string>("TypeProcess")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fastserver_type_process");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fastserver_user_id");

                    b.HasKey("LogId");

                    b.HasIndex("LogDateIn");

                    b.HasIndex("LogState");

                    b.HasIndex("MicroserviceName");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("FastServer_LogServices_Header", (string)null);

                    b.HasData(
                        new
                        {
                            LogId = 1L,
                            HttpMethod = "POST",
                            IpFs = "192.168.1.100",
                            LogDateIn = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            LogDateOut = new DateTime(2025, 1, 1, 10, 0, 0, 150, DateTimeKind.Utc),
                            LogMethodName = "AuthenticateUser",
                            LogMethodUrl = "/api/users/authenticate",
                            LogState = "Completed",
                            MicroserviceName = "AuthService",
                            RequestDuration = 150L,
                            SessionId = "SES-001",
                            TransactionId = "TRX-001-2025",
                            TypeProcess = "Authentication",
                            UserId = "admin"
                        },
                        new
                        {
                            LogId = 2L,
                            HttpMethod = "GET",
                            IpFs = "192.168.1.101",
                            LogDateIn = new DateTime(2025, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc),
                            LogDateOut = new DateTime(2025, 1, 1, 10, 5, 0, 320, DateTimeKind.Utc),
                            LogMethodName = "SearchProducts",
                            LogMethodUrl = "/api/products/search",
                            LogState = "Completed",
                            MicroserviceName = "ProductService",
                            RequestDuration = 320L,
                            SessionId = "SES-002",
                            TransactionId = "TRX-002-2025",
                            TypeProcess = "Query",
                            UserId = "user001"
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogServicesHeaderHistorico", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fastserver_error_code");

                    b.Property<string>("ErrorDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("fastserver_error_description");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fastserver_http_method");

                    b.Property<string>("IpFs")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fastserver_ip_fs");

                    b.Property<DateTime>("LogDateIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_log_date_in");

                    b.Property<DateTime>("LogDateOut")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_log_date_out");

                    b.Property<long?>("LogFsId")
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_fs_id");

                    b.Property<string>("LogMethodName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fastserver_log_method_name");

                    b.Property<string>("LogMethodUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fastserver_log_method_url");

                    b.Property<string>("LogNodo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fastserver_log_nodo");

                    b.Property<string>("LogState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fastserver_log_state");

                    b.Property<string>("MethodDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("fastserver_method_description");

                    b.Property<string>("MicroserviceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fastserver_microservice_name");

                    b.Property<long?>("RequestDuration")
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_request_duration");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_request_id");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fastserver_session_id");

                    b.Property<string>("TciIpPort")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fastserver_tci_ip_port");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fastserver_transaction_id");

                    b.Property<string>("TypeProcess")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fastserver_type_process");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fastserver_user_id");

                    b.HasKey("LogId");

                    b.HasIndex("LogDateIn");

                    b.HasIndex("LogState");

                    b.ToTable("FastServer_LogServices_Header_Historico", (string)null);

                    b.HasData(
                        new
                        {
                            LogId = 1L,
                            HttpMethod = "POST",
                            IpFs = "192.168.1.50",
                            LogDateIn = new DateTime(2024, 12, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            LogDateOut = new DateTime(2024, 12, 15, 10, 0, 0, 145, DateTimeKind.Utc),
                            LogMethodName = "AuthenticateUser",
                            LogMethodUrl = "/api/users/authenticate",
                            LogState = "Completed",
                            MicroserviceName = "AuthService",
                            RequestDuration = 145L,
                            SessionId = "SES-HIST-001",
                            TransactionId = "TRX-HIST-001-2024",
                            TypeProcess = "Authentication",
                            UserId = "admin"
                        },
                        new
                        {
                            LogId = 2L,
                            HttpMethod = "GET",
                            IpFs = "192.168.1.51",
                            LogDateIn = new DateTime(2024, 12, 15, 10, 10, 0, 0, DateTimeKind.Utc),
                            LogDateOut = new DateTime(2024, 12, 15, 10, 10, 0, 280, DateTimeKind.Utc),
                            LogMethodName = "SearchProducts",
                            LogMethodUrl = "/api/products/search",
                            LogState = "Completed",
                            MicroserviceName = "ProductService",
                            RequestDuration = 280L,
                            SessionId = "SES-HIST-002",
                            TransactionId = "TRX-HIST-002-2024",
                            TypeProcess = "Query",
                            UserId = "user001"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
