// <auto-generated />
using System;
using FastServer.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastServer.Infrastructure.Data.Migrations.SqlServer
{
    [DbContext(typeof(SqlServerDbContext))]
    [Migration("20260123201324_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastServer.Domain.Entities.LogMicroservice", b =>
                {
                    b.Property<long>("LogId")
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_id");

                    b.Property<string>("LogMicroserviceText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fastserver_logmicroservice_text");

                    b.HasKey("LogId");

                    b.HasIndex("LogId");

                    b.ToTable("FastServer_LogMicroservice", (string)null);

                    b.HasData(
                        new
                        {
                            LogId = 1L,
                            LogMicroserviceText = "[AuthService] Inicio de autenticación para usuario: admin"
                        },
                        new
                        {
                            LogId = 2L,
                            LogMicroserviceText = "[CustomerService] Consultando lista de clientes con filtro activo"
                        },
                        new
                        {
                            LogId = 3L,
                            LogMicroserviceText = "[OrderService] Error: No se pudo conectar con InventoryService después de 3 reintentos"
                        },
                        new
                        {
                            LogId = 4L,
                            LogMicroserviceText = "[ProductService] Búsqueda ejecutada: 'laptop gaming' - 15 resultados encontrados"
                        },
                        new
                        {
                            LogId = 5L,
                            LogMicroserviceText = "[ReportService] Generando reporte mensual de ventas - Timeout alcanzado en agregación de datos"
                        },
                        new
                        {
                            LogId = 7L,
                            LogMicroserviceText = "[PaymentService] Pago procesado exitosamente - Monto: $1,250.00 - Método: Tarjeta de crédito"
                        },
                        new
                        {
                            LogId = 8L,
                            LogMicroserviceText = "[NotificationService] Envío de notificación cancelado por solicitud del usuario"
                        },
                        new
                        {
                            LogId = 9L,
                            LogMicroserviceText = "[InventoryService] Actualización de stock completada - 50 productos modificados"
                        },
                        new
                        {
                            LogId = 10L,
                            LogMicroserviceText = "[BatchService] Procesamiento por lotes iniciado - 1000 registros pendientes"
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogMicroserviceHistorico", b =>
                {
                    b.Property<long>("LogId")
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_id");

                    b.Property<string>("LogMicroserviceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fastserver_logmicroservice_text");

                    b.HasKey("LogId");

                    b.HasIndex("LogId");

                    b.ToTable("FastServer_LogMicroservice_Historico", (string)null);
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogServicesContent", b =>
                {
                    b.Property<long>("LogId")
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_id");

                    b.Property<string>("ContentNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fastserver_no");

                    b.Property<string>("LogServicesContentText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fastserver_logservices_content_text");

                    b.HasKey("LogId", "ContentNo");

                    b.HasIndex("LogId");

                    b.ToTable("FastServer_LogServices_Content", (string)null);

                    b.HasData(
                        new
                        {
                            LogId = 1L,
                            ContentNo = "001",
                            LogServicesContentText = "{\"username\": \"admin\", \"timestamp\": \"2025-01-01T10:00:00Z\", \"ip\": \"192.168.1.100\"}"
                        },
                        new
                        {
                            LogId = 3L,
                            ContentNo = "001",
                            LogServicesContentText = "{\"orderId\": null, \"error\": \"ConnectionRefused\", \"service\": \"InventoryService\", \"retries\": 3}"
                        },
                        new
                        {
                            LogId = 5L,
                            ContentNo = "001",
                            LogServicesContentText = "{\"reportType\": \"MonthlySales\", \"month\": \"December\", \"year\": 2024, \"status\": \"timeout\"}"
                        },
                        new
                        {
                            LogId = 7L,
                            ContentNo = "001",
                            LogServicesContentText = "{\"transactionId\": \"PAY-12345\", \"amount\": 1250.00, \"currency\": \"USD\", \"method\": \"credit_card\"}"
                        },
                        new
                        {
                            LogId = 9L,
                            ContentNo = "001",
                            LogServicesContentText = "{\"warehouseId\": \"WH-001\", \"productsUpdated\": 50, \"operation\": \"stock_adjustment\"}"
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogServicesContentHistorico", b =>
                {
                    b.Property<long>("LogId")
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_id");

                    b.Property<string>("ContentNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fastserver_no");

                    b.Property<string>("LogServicesContentText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fastserver_logservices_content_text");

                    b.HasKey("LogId", "ContentNo");

                    b.HasIndex("LogId");

                    b.ToTable("FastServer_LogServices_Content_Historico", (string)null);
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogServicesHeader", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fastserver_error_code");

                    b.Property<string>("ErrorDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("fastserver_error_description");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("fastserver_http_method");

                    b.Property<string>("IpFs")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fastserver_ip_fs");

                    b.Property<DateTime>("LogDateIn")
                        .HasColumnType("datetime2")
                        .HasColumnName("fastserver_log_date_in");

                    b.Property<DateTime>("LogDateOut")
                        .HasColumnType("datetime2")
                        .HasColumnName("fastserver_log_date_out");

                    b.Property<long?>("LogFsId")
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_fs_id");

                    b.Property<string>("LogMethodName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fastserver_log_method_name");

                    b.Property<string>("LogMethodUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("fastserver_log_method_url");

                    b.Property<string>("LogNodo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fastserver_log_nodo");

                    b.Property<string>("LogState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fastserver_log_state");

                    b.Property<string>("MethodDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("fastserver_method_description");

                    b.Property<string>("MicroserviceName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fastserver_microservice_name");

                    b.Property<long?>("RequestDuration")
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_request_duration");

                    b.Property<long?>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_request_id");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fastserver_session_id");

                    b.Property<string>("TciIpPort")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fastserver_tci_ip_port");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fastserver_transaction_id");

                    b.Property<string>("TypeProcess")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fastserver_type_process");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fastserver_user_id");

                    b.HasKey("LogId");

                    b.HasIndex("LogDateIn");

                    b.HasIndex("LogState");

                    b.HasIndex("MicroserviceName");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("FastServer_LogServices_Header", (string)null);

                    b.HasData(
                        new
                        {
                            LogId = 1L,
                            HttpMethod = "POST",
                            IpFs = "192.168.1.100",
                            LogDateIn = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            LogDateOut = new DateTime(2025, 1, 1, 10, 0, 0, 150, DateTimeKind.Utc),
                            LogMethodName = "AuthenticateUser",
                            LogMethodUrl = "/api/users/authenticate",
                            LogState = "Completed",
                            MicroserviceName = "AuthService",
                            RequestDuration = 150L,
                            SessionId = "SES-001",
                            TransactionId = "TRX-001-2025",
                            TypeProcess = "Authentication",
                            UserId = "admin"
                        },
                        new
                        {
                            LogId = 2L,
                            HttpMethod = "GET",
                            IpFs = "192.168.1.101",
                            LogDateIn = new DateTime(2025, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc),
                            LogDateOut = new DateTime(2025, 1, 1, 10, 5, 0, 85, DateTimeKind.Utc),
                            LogMethodName = "GetCustomerList",
                            LogMethodUrl = "/api/customers/list",
                            LogState = "Completed",
                            MicroserviceName = "CustomerService",
                            RequestDuration = 85L,
                            SessionId = "SES-002",
                            TransactionId = "TRX-002-2025",
                            TypeProcess = "Query",
                            UserId = "user001"
                        },
                        new
                        {
                            LogId = 3L,
                            ErrorCode = "ORD-500",
                            ErrorDescription = "Error de conexión con el servicio de inventario",
                            HttpMethod = "POST",
                            IpFs = "192.168.1.102",
                            LogDateIn = new DateTime(2025, 1, 1, 10, 10, 0, 0, DateTimeKind.Utc),
                            LogDateOut = new DateTime(2025, 1, 1, 10, 10, 5, 200, DateTimeKind.Utc),
                            LogMethodName = "CreateOrder",
                            LogMethodUrl = "/api/orders/create",
                            LogState = "Failed",
                            MicroserviceName = "OrderService",
                            RequestDuration = 5200L,
                            SessionId = "SES-003",
                            TransactionId = "TRX-003-2025",
                            TypeProcess = "Transaction",
                            UserId = "user002"
                        },
                        new
                        {
                            LogId = 4L,
                            HttpMethod = "GET",
                            IpFs = "192.168.1.103",
                            LogDateIn = new DateTime(2025, 1, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            LogDateOut = new DateTime(2025, 1, 1, 10, 15, 0, 320, DateTimeKind.Utc),
                            LogMethodName = "SearchProducts",
                            LogMethodUrl = "/api/products/search",
                            LogState = "Completed",
                            MicroserviceName = "ProductService",
                            RequestDuration = 320L,
                            SessionId = "SES-004",
                            TransactionId = "TRX-004-2025",
                            TypeProcess = "Query",
                            UserId = "user003"
                        },
                        new
                        {
                            LogId = 5L,
                            ErrorCode = "RPT-408",
                            ErrorDescription = "Tiempo de espera agotado generando reporte mensual",
                            HttpMethod = "POST",
                            IpFs = "192.168.1.100",
                            LogDateIn = new DateTime(2025, 1, 1, 10, 20, 0, 0, DateTimeKind.Utc),
                            LogDateOut = new DateTime(2025, 1, 1, 10, 20, 30, 500, DateTimeKind.Utc),
                            LogMethodName = "GenerateReport",
                            LogMethodUrl = "/api/reports/generate",
                            LogState = "Timeout",
                            MicroserviceName = "ReportService",
                            RequestDuration = 30500L,
                            SessionId = "SES-005",
                            TransactionId = "TRX-005-2025",
                            TypeProcess = "Report",
                            UserId = "admin"
                        },
                        new
                        {
                            LogId = 6L,
                            HttpMethod = "GET",
                            IpFs = "192.168.1.200",
                            LogDateIn = new DateTime(2025, 1, 1, 10, 25, 0, 0, DateTimeKind.Utc),
                            LogDateOut = new DateTime(2025, 1, 1, 10, 25, 0, 45, DateTimeKind.Utc),
                            LogMethodName = "HealthCheck",
                            LogMethodUrl = "/api/health",
                            LogState = "Completed",
                            MicroserviceName = "HealthService",
                            RequestDuration = 45L,
                            TransactionId = "TRX-006-2025",
                            TypeProcess = "Health"
                        },
                        new
                        {
                            LogId = 7L,
                            HttpMethod = "POST",
                            IpFs = "192.168.1.104",
                            LogDateIn = new DateTime(2025, 1, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            LogDateOut = new DateTime(2025, 1, 1, 10, 30, 1, 850, DateTimeKind.Utc),
                            LogMethodName = "ProcessPayment",
                            LogMethodUrl = "/api/payments/process",
                            LogState = "Completed",
                            MicroserviceName = "PaymentService",
                            RequestDuration = 1850L,
                            SessionId = "SES-006",
                            TransactionId = "TRX-007-2025",
                            TypeProcess = "Transaction",
                            UserId = "user004"
                        },
                        new
                        {
                            LogId = 8L,
                            ErrorCode = "NTF-499",
                            ErrorDescription = "Operación cancelada por el usuario",
                            HttpMethod = "POST",
                            IpFs = "192.168.1.50",
                            LogDateIn = new DateTime(2025, 1, 1, 10, 35, 0, 0, DateTimeKind.Utc),
                            LogDateOut = new DateTime(2025, 1, 1, 10, 35, 0, 125, DateTimeKind.Utc),
                            LogMethodName = "SendNotification",
                            LogMethodUrl = "/api/notifications/send",
                            LogState = "Cancelled",
                            MicroserviceName = "NotificationService",
                            RequestDuration = 125L,
                            TransactionId = "TRX-008-2025",
                            TypeProcess = "Notification",
                            UserId = "system"
                        },
                        new
                        {
                            LogId = 9L,
                            HttpMethod = "PUT",
                            IpFs = "192.168.1.105",
                            LogDateIn = new DateTime(2025, 1, 1, 10, 40, 0, 0, DateTimeKind.Utc),
                            LogDateOut = new DateTime(2025, 1, 1, 10, 40, 2, 100, DateTimeKind.Utc),
                            LogMethodName = "UpdateInventory",
                            LogMethodUrl = "/api/inventory/update",
                            LogState = "Completed",
                            MicroserviceName = "InventoryService",
                            RequestDuration = 2100L,
                            SessionId = "SES-007",
                            TransactionId = "TRX-009-2025",
                            TypeProcess = "Update",
                            UserId = "warehouse001"
                        },
                        new
                        {
                            LogId = 10L,
                            HttpMethod = "POST",
                            IpFs = "192.168.1.60",
                            LogDateIn = new DateTime(2025, 1, 1, 10, 45, 0, 0, DateTimeKind.Utc),
                            LogDateOut = new DateTime(2025, 1, 1, 10, 45, 0, 95, DateTimeKind.Utc),
                            LogMethodName = "ProcessBatch",
                            LogMethodUrl = "/api/batch/process",
                            LogState = "InProgress",
                            MicroserviceName = "BatchService",
                            RequestDuration = 95L,
                            TransactionId = "TRX-010-2025",
                            TypeProcess = "Batch",
                            UserId = "scheduler"
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogServicesHeaderHistorico", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fastserver_error_code");

                    b.Property<string>("ErrorDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("fastserver_error_description");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("fastserver_http_method");

                    b.Property<string>("IpFs")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fastserver_ip_fs");

                    b.Property<DateTime>("LogDateIn")
                        .HasColumnType("datetime2")
                        .HasColumnName("fastserver_log_date_in");

                    b.Property<DateTime>("LogDateOut")
                        .HasColumnType("datetime2")
                        .HasColumnName("fastserver_log_date_out");

                    b.Property<long?>("LogFsId")
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_log_fs_id");

                    b.Property<string>("LogMethodName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fastserver_log_method_name");

                    b.Property<string>("LogMethodUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("fastserver_log_method_url");

                    b.Property<string>("LogNodo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fastserver_log_nodo");

                    b.Property<string>("LogState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fastserver_log_state");

                    b.Property<string>("MethodDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("fastserver_method_description");

                    b.Property<string>("MicroserviceName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fastserver_microservice_name");

                    b.Property<long?>("RequestDuration")
                        .HasColumnType("bigint")
                        .HasColumnName("fastserver_request_duration");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fastserver_request_id");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fastserver_session_id");

                    b.Property<string>("TciIpPort")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fastserver_tci_ip_port");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fastserver_transaction_id");

                    b.Property<string>("TypeProcess")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fastserver_type_process");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fastserver_user_id");

                    b.HasKey("LogId");

                    b.HasIndex("LogDateIn");

                    b.HasIndex("LogState");

                    b.ToTable("FastServer_LogServices_Header_Historico", (string)null);
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogMicroservice", b =>
                {
                    b.HasOne("FastServer.Domain.Entities.LogServicesHeader", "LogServicesHeader")
                        .WithMany("LogMicroservices")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogServicesHeader");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogMicroserviceHistorico", b =>
                {
                    b.HasOne("FastServer.Domain.Entities.LogServicesHeaderHistorico", "LogServicesHeader")
                        .WithMany("LogMicroservices")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogServicesHeader");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogServicesContent", b =>
                {
                    b.HasOne("FastServer.Domain.Entities.LogServicesHeader", "LogServicesHeader")
                        .WithMany("LogServicesContents")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogServicesHeader");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogServicesContentHistorico", b =>
                {
                    b.HasOne("FastServer.Domain.Entities.LogServicesHeaderHistorico", "LogServicesHeader")
                        .WithMany("LogServicesContents")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogServicesHeader");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogServicesHeader", b =>
                {
                    b.Navigation("LogMicroservices");

                    b.Navigation("LogServicesContents");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.LogServicesHeaderHistorico", b =>
                {
                    b.Navigation("LogMicroservices");

                    b.Navigation("LogServicesContents");
                });
#pragma warning restore 612, 618
        }
    }
}
