// <auto-generated />
using System;
using FastServer.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastServer.Infrastructure.Data.Migrations.SqlServer
{
    [DbContext(typeof(SqlServerDbContext))]
    [Migration("20260209220606_OptimizeIndexesAndAuth")]
    partial class OptimizeIndexesAndAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.ActivityLog", b =>
                {
                    b.Property<Guid>("ActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("activity_log_id");

                    b.Property<string>("ActivityLogDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("activity_log_description");

                    b.Property<Guid?>("ActivityLogEntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("activity_log_entity_id");

                    b.Property<string>("ActivityLogEntityName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("activity_log_entity_name");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at");

                    b.Property<long?>("EventTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_type_id");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modify_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("ActivityLogId");

                    b.HasIndex("ActivityLogEntityName");

                    b.HasIndex("CreateAt");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CreateAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ActivityLog_UserId_CreateAt_Desc");

                    b.ToTable("activity_logs", (string)null);

                    b.HasData(
                        new
                        {
                            ActivityLogId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ActivityLogDescription = "AuthService registered successfully",
                            ActivityLogEntityId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ActivityLogEntityName = "MicroserviceRegister",
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 1L,
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            ActivityLogId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ActivityLogDescription = "ProductService configuration updated",
                            ActivityLogEntityId = new Guid("20000000-0000-0000-0000-000000000002"),
                            ActivityLogEntityName = "MicroserviceRegister",
                            CreateAt = new DateTime(2025, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc),
                            EventTypeId = 2L,
                            ModifyAt = new DateTime(2025, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.CoreConnectorCredential", b =>
                {
                    b.Property<long>("CoreConnectorCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("core_connector_credential_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CoreConnectorCredentialId"));

                    b.Property<string>("CoreConnectorCredentialKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("core_connector_credential_key");

                    b.Property<string>("CoreConnectorCredentialPass")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("core_connector_credential_pass");

                    b.Property<string>("CoreConnectorCredentialUser")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("core_connector_credential_user");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modify_at");

                    b.HasKey("CoreConnectorCredentialId");

                    b.HasIndex("CoreConnectorCredentialUser")
                        .IsUnique()
                        .HasDatabaseName("UX_CoreConnectorCredential_User")
                        .HasFilter("[core_connector_credential_user] IS NOT NULL");

                    b.ToTable("core_connector_credentials", (string)null);

                    b.HasData(
                        new
                        {
                            CoreConnectorCredentialId = 1L,
                            CoreConnectorCredentialKey = "api_key_001",
                            CoreConnectorCredentialPass = "encrypted_pass_001",
                            CoreConnectorCredentialUser = "auth_service_user",
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CoreConnectorCredentialId = 2L,
                            CoreConnectorCredentialKey = "api_key_002",
                            CoreConnectorCredentialPass = "encrypted_pass_002",
                            CoreConnectorCredentialUser = "product_service_user",
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.EventType", b =>
                {
                    b.Property<long>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventTypeId"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at");

                    b.Property<string>("EventTypeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("event_type_description");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modify_at");

                    b.HasKey("EventTypeId");

                    b.HasIndex("EventTypeDescription");

                    b.ToTable("event_types", (string)null);

                    b.HasData(
                        new
                        {
                            EventTypeId = 1L,
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeDescription = "Microservice Registration",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            EventTypeId = 2L,
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeDescription = "Configuration Change",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroserviceCoreConnector", b =>
                {
                    b.Property<long>("MicroserviceCoreConnectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("microservice_core_connector_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MicroserviceCoreConnectorId"));

                    b.Property<long?>("CoreConnectorCredentialId")
                        .HasColumnType("bigint")
                        .HasColumnName("core_connector_credential_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at");

                    b.Property<long?>("MicroserviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("microservice_id");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modify_at");

                    b.HasKey("MicroserviceCoreConnectorId");

                    b.HasIndex("CoreConnectorCredentialId");

                    b.HasIndex("MicroserviceId");

                    b.ToTable("microservice_core_connector", (string)null);

                    b.HasData(
                        new
                        {
                            MicroserviceCoreConnectorId = 1L,
                            CoreConnectorCredentialId = 1L,
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroserviceId = 1L,
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MicroserviceCoreConnectorId = 2L,
                            CoreConnectorCredentialId = 2L,
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroserviceId = 2L,
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroserviceMethod", b =>
                {
                    b.Property<long>("MicroserviceMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("microservice_method_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MicroserviceMethodId"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at");

                    b.Property<long>("MicroserviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("microservice_id");

                    b.Property<bool?>("MicroserviceMethodDelete")
                        .HasColumnType("bit")
                        .HasColumnName("microservice_method_delete");

                    b.Property<string>("MicroserviceMethodName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("microservice_method_name");

                    b.Property<string>("MicroserviceMethodUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("microservice_method_url");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modify_at");

                    b.HasKey("MicroserviceMethodId");

                    b.HasIndex("MicroserviceId");

                    b.HasIndex("MicroserviceMethodName");

                    b.ToTable("microservice_methods", (string)null);

                    b.HasData(
                        new
                        {
                            MicroserviceMethodId = 1L,
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroserviceId = 1L,
                            MicroserviceMethodDelete = false,
                            MicroserviceMethodName = "AuthenticateUser",
                            MicroserviceMethodUrl = "/api/users/authenticate",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MicroserviceMethodId = 2L,
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroserviceId = 2L,
                            MicroserviceMethodDelete = false,
                            MicroserviceMethodName = "SearchProducts",
                            MicroserviceMethodUrl = "/api/products/search",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroserviceRegister", b =>
                {
                    b.Property<long>("MicroserviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("microservice_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MicroserviceId"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("delete_at");

                    b.Property<bool?>("MicroserviceActive")
                        .HasColumnType("bit")
                        .HasColumnName("microservice_active");

                    b.Property<long?>("MicroserviceClusterId")
                        .HasColumnType("bigint")
                        .HasColumnName("microservice_cluster_id");

                    b.Property<bool?>("MicroserviceCoreConnection")
                        .HasColumnType("bit")
                        .HasColumnName("microservice_core_connection");

                    b.Property<bool?>("MicroserviceDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("microservice_deleted");

                    b.Property<string>("MicroserviceName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("microservice_name");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modify_at");

                    b.HasKey("MicroserviceId");

                    b.HasIndex("MicroserviceClusterId");

                    b.HasIndex("MicroserviceName");

                    b.HasIndex("MicroserviceClusterId", "MicroserviceName")
                        .HasDatabaseName("IX_MicroserviceRegister_ClusterId_Name");

                    b.ToTable("microservice_registers", (string)null);

                    b.HasData(
                        new
                        {
                            MicroserviceId = 1L,
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroserviceActive = true,
                            MicroserviceClusterId = 1L,
                            MicroserviceCoreConnection = true,
                            MicroserviceDeleted = false,
                            MicroserviceName = "AuthService",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MicroserviceId = 2L,
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroserviceActive = true,
                            MicroserviceClusterId = 1L,
                            MicroserviceCoreConnection = true,
                            MicroserviceDeleted = false,
                            MicroserviceName = "ProductService",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroservicesCluster", b =>
                {
                    b.Property<long>("MicroservicesClusterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("microservices_cluster_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MicroservicesClusterId"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("delete_at");

                    b.Property<bool?>("MicroservicesClusterActive")
                        .HasColumnType("bit")
                        .HasColumnName("microservices_cluster_active");

                    b.Property<bool?>("MicroservicesClusterDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("microservices_cluster_deleted");

                    b.Property<string>("MicroservicesClusterName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("microservices_cluster_name");

                    b.Property<string>("MicroservicesClusterServerIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("microservices_cluster_server_ip");

                    b.Property<string>("MicroservicesClusterServerName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("microservices_cluster_server_name");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modify_at");

                    b.HasKey("MicroservicesClusterId");

                    b.HasIndex("MicroservicesClusterName");

                    b.ToTable("microservices_clusters", (string)null);

                    b.HasData(
                        new
                        {
                            MicroservicesClusterId = 1L,
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroservicesClusterActive = true,
                            MicroservicesClusterDeleted = false,
                            MicroservicesClusterName = "Production Cluster",
                            MicroservicesClusterServerIp = "10.0.1.100",
                            MicroservicesClusterServerName = "prod-cluster-01",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MicroservicesClusterId = 2L,
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroservicesClusterActive = true,
                            MicroservicesClusterDeleted = false,
                            MicroservicesClusterName = "Development Cluster",
                            MicroservicesClusterServerIp = "10.0.2.100",
                            MicroservicesClusterServerName = "dev-cluster-01",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("modify_at");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<bool?>("UserActive")
                        .HasColumnType("bit")
                        .HasColumnName("user_active");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPeoplesoft")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_peoplesoft");

                    b.HasKey("UserId");

                    b.HasIndex("UserEmail")
                        .IsUnique()
                        .HasFilter("[user_email] IS NOT NULL");

                    b.HasIndex("UserPeoplesoft");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$6K8V4pZ4rX5YqLH8wX5Z8OZx3Q2ZsN5Y8mWvP5X8wX5Z8OZx3Q2Zs",
                            UserActive = true,
                            UserEmail = "admin@fastserver.com",
                            UserName = "Admin User",
                            UserPeoplesoft = "PS001"
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$7L9W5qA5sY6ZrMI9xY6A9PAy4R3AtO6Z9nXwQ6Y9xY6A9PAy4R3At",
                            UserActive = true,
                            UserEmail = "developer@fastserver.com",
                            UserName = "Developer User",
                            UserPeoplesoft = "PS002"
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.ActivityLog", b =>
                {
                    b.HasOne("FastServer.Domain.Entities.Microservices.EventType", "EventType")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FastServer.Domain.Entities.Microservices.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EventType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroserviceCoreConnector", b =>
                {
                    b.HasOne("FastServer.Domain.Entities.Microservices.CoreConnectorCredential", "CoreConnectorCredential")
                        .WithMany("MicroserviceCoreConnectors")
                        .HasForeignKey("CoreConnectorCredentialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FastServer.Domain.Entities.Microservices.MicroserviceRegister", "MicroserviceRegister")
                        .WithMany("MicroserviceCoreConnectors")
                        .HasForeignKey("MicroserviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CoreConnectorCredential");

                    b.Navigation("MicroserviceRegister");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroserviceMethod", b =>
                {
                    b.HasOne("FastServer.Domain.Entities.Microservices.MicroserviceRegister", "MicroserviceRegister")
                        .WithMany("MicroserviceMethods")
                        .HasForeignKey("MicroserviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MicroserviceRegister");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroserviceRegister", b =>
                {
                    b.HasOne("FastServer.Domain.Entities.Microservices.MicroservicesCluster", "MicroserviceCluster")
                        .WithMany("MicroserviceRegisters")
                        .HasForeignKey("MicroserviceClusterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MicroserviceCluster");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.CoreConnectorCredential", b =>
                {
                    b.Navigation("MicroserviceCoreConnectors");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.EventType", b =>
                {
                    b.Navigation("ActivityLogs");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroserviceRegister", b =>
                {
                    b.Navigation("MicroserviceCoreConnectors");

                    b.Navigation("MicroserviceMethods");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroservicesCluster", b =>
                {
                    b.Navigation("MicroserviceRegisters");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.User", b =>
                {
                    b.Navigation("ActivityLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
