// <auto-generated />
using System;
using FastServer.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FastServer.Infrastructure.Data.Migrations.PostgreSqlMicroservices
{
    [DbContext(typeof(PostgreSqlMicroservicesDbContext))]
    partial class PostgreSqlMicroservicesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.ActivityLog", b =>
                {
                    b.Property<Guid>("ActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_activity_log_id");

                    b.Property<string>("ActivityLogDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("fastserver_activity_log_description");

                    b.Property<Guid?>("ActivityLogEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_activity_log_entity_id");

                    b.Property<string>("ActivityLogEntityName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fastserver_activity_log_entity_name");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_create_at");

                    b.Property<Guid?>("EventTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_event_type_id");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_modify_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_user_id");

                    b.HasKey("ActivityLogId");

                    b.HasIndex("ActivityLogEntityName")
                        .HasDatabaseName("IX_FastServer_ActivityLog_EntityName");

                    b.HasIndex("CreateAt")
                        .HasDatabaseName("IX_FastServer_ActivityLog_CreateAt");

                    b.HasIndex("EventTypeId")
                        .HasDatabaseName("IX_FastServer_ActivityLog_EventTypeId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_FastServer_ActivityLog_UserId");

                    b.HasIndex("UserId", "CreateAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_FastServer_ActivityLog_UserId_CreateAt_Desc");

                    b.ToTable("FastServer_ActivityLog", (string)null);

                    b.HasData(
                        new
                        {
                            ActivityLogId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ActivityLogDescription = "AuthService registered successfully",
                            ActivityLogEntityId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ActivityLogEntityName = "MicroserviceRegister",
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeId = new Guid("ee000000-0000-0000-0000-000000000001"),
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            ActivityLogId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ActivityLogDescription = "ProductService configuration updated",
                            ActivityLogEntityId = new Guid("20000000-0000-0000-0000-000000000002"),
                            ActivityLogEntityName = "MicroserviceRegister",
                            CreateAt = new DateTime(2025, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc),
                            EventTypeId = new Guid("ee000000-0000-0000-0000-000000000002"),
                            ModifyAt = new DateTime(2025, 1, 1, 10, 5, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("00000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.CoreConnectorCredential", b =>
                {
                    b.Property<Guid>("CoreConnectorCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_core_connector_credential_id");

                    b.Property<string>("CoreConnectorCredentialKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fastserver_core_connector_credential_key");

                    b.Property<string>("CoreConnectorCredentialPass")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fastserver_core_connector_credential_pass");

                    b.Property<string>("CoreConnectorCredentialUser")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fastserver_core_connector_credential_user");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_create_at");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_modify_at");

                    b.HasKey("CoreConnectorCredentialId");

                    b.HasIndex("CoreConnectorCredentialUser")
                        .IsUnique()
                        .HasDatabaseName("UX_FastServer_CoreConnector_Credential_User");

                    b.ToTable("FastServer_CoreConnector_Credential", (string)null);

                    b.HasData(
                        new
                        {
                            CoreConnectorCredentialId = new Guid("ff000000-0000-0000-0000-000000000001"),
                            CoreConnectorCredentialKey = "api_key_001",
                            CoreConnectorCredentialPass = "encrypted_pass_001",
                            CoreConnectorCredentialUser = "auth_service_user",
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CoreConnectorCredentialId = new Guid("ff000000-0000-0000-0000-000000000002"),
                            CoreConnectorCredentialKey = "api_key_002",
                            CoreConnectorCredentialPass = "encrypted_pass_002",
                            CoreConnectorCredentialUser = "product_service_user",
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.EventType", b =>
                {
                    b.Property<Guid>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_event_type_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_create_at");

                    b.Property<string>("EventTypeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fastserver_event_type_description");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_modify_at");

                    b.HasKey("EventTypeId");

                    b.HasIndex("EventTypeDescription")
                        .HasDatabaseName("IX_FastServer_EventType_Description");

                    b.ToTable("FastServer_EventType", (string)null);

                    b.HasData(
                        new
                        {
                            EventTypeId = new Guid("ee000000-0000-0000-0000-000000000001"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeDescription = "Microservice Registration",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            EventTypeId = new Guid("ee000000-0000-0000-0000-000000000002"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventTypeDescription = "Configuration Change",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.FastServerCluster", b =>
                {
                    b.Property<Guid>("FastServerClusterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_cluster_id");

                    b.Property<DateTimeOffset?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_create_at");

                    b.Property<DateTimeOffset?>("DeleteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_delete_at");

                    b.Property<bool?>("FastServerClusterActive")
                        .HasColumnType("boolean")
                        .HasColumnName("fastserver_cluster_active");

                    b.Property<bool?>("FastServerClusterDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("fastserver_cluster_delete");

                    b.Property<string>("FastServerClusterName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("fastserver_cluster_name");

                    b.Property<string>("FastServerClusterServerIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fastserver_cluster_server_ip");

                    b.Property<string>("FastServerClusterServerName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("fastserver_cluster_server_name");

                    b.Property<string>("FastServerClusterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fastserver_cluster_url");

                    b.Property<string>("FastServerClusterVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fastserver_cluster_version");

                    b.Property<DateTimeOffset?>("ModifyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_modify_at");

                    b.HasKey("FastServerClusterId");

                    b.HasIndex("FastServerClusterName")
                        .HasDatabaseName("IX_FastServer_Cluster_Name");

                    b.ToTable("FastServer_Cluster", (string)null);

                    b.HasData(
                        new
                        {
                            FastServerClusterId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CreateAt = new DateTimeOffset(new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FastServerClusterActive = true,
                            FastServerClusterDelete = false,
                            FastServerClusterName = "FS Production Cluster",
                            FastServerClusterServerIp = "10.10.1.100",
                            FastServerClusterServerName = "fs-prod-node-01",
                            FastServerClusterUrl = "https://fs-prod.davivienda.hn:8443",
                            FastServerClusterVersion = "1.0.0",
                            ModifyAt = new DateTimeOffset(new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            FastServerClusterId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CreateAt = new DateTimeOffset(new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FastServerClusterActive = true,
                            FastServerClusterDelete = false,
                            FastServerClusterName = "FS Development Cluster",
                            FastServerClusterServerIp = "10.10.2.100",
                            FastServerClusterServerName = "fs-dev-node-01",
                            FastServerClusterUrl = "https://fs-dev.davivienda.hn:8443",
                            FastServerClusterVersion = "1.0.0-dev",
                            ModifyAt = new DateTimeOffset(new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroserviceCoreConnector", b =>
                {
                    b.Property<Guid>("MicroserviceCoreConnectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_microservice_core_connector_id");

                    b.Property<Guid?>("CoreConnectorCredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_core_connector_credential_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_create_at");

                    b.Property<Guid?>("MicroserviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_microservice_id");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_modify_at");

                    b.HasKey("MicroserviceCoreConnectorId");

                    b.HasIndex("CoreConnectorCredentialId")
                        .HasDatabaseName("IX_FastServer_Microservice_CoreConnector_CredentialId");

                    b.HasIndex("MicroserviceId")
                        .HasDatabaseName("IX_FastServer_Microservice_CoreConnector_MicroserviceId");

                    b.ToTable("FastServer_Microservice_CoreConnector", (string)null);

                    b.HasData(
                        new
                        {
                            MicroserviceCoreConnectorId = new Guid("11000000-0000-0000-0000-000000000001"),
                            CoreConnectorCredentialId = new Guid("ff000000-0000-0000-0000-000000000001"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroserviceId = new Guid("cc000000-0000-0000-0000-000000000001"),
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MicroserviceCoreConnectorId = new Guid("11000000-0000-0000-0000-000000000002"),
                            CoreConnectorCredentialId = new Guid("ff000000-0000-0000-0000-000000000002"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroserviceId = new Guid("cc000000-0000-0000-0000-000000000002"),
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroserviceMethod", b =>
                {
                    b.Property<Guid>("MicroserviceMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_microservice_method_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_create_at");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fastserver_http_method");

                    b.Property<Guid>("MicroserviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_microservice_id");

                    b.Property<bool?>("MicroserviceMethodDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("fastserver_microservice_method_delete");

                    b.Property<string>("MicroserviceMethodName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fastserver_microservice_method_name");

                    b.Property<string>("MicroserviceMethodUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fastserver_microservice_method_url");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_modify_at");

                    b.HasKey("MicroserviceMethodId");

                    b.HasIndex("MicroserviceId")
                        .HasDatabaseName("IX_FastServer_Microservice_Method_MicroserviceId");

                    b.HasIndex("MicroserviceMethodName")
                        .HasDatabaseName("IX_FastServer_Microservice_Method_Name");

                    b.ToTable("FastServer_Microservice_Method", (string)null);

                    b.HasData(
                        new
                        {
                            MicroserviceMethodId = new Guid("dd000000-0000-0000-0000-000000000001"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            HttpMethod = "POST",
                            MicroserviceId = new Guid("cc000000-0000-0000-0000-000000000001"),
                            MicroserviceMethodDelete = false,
                            MicroserviceMethodName = "AuthenticateUser",
                            MicroserviceMethodUrl = "/api/users/authenticate",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MicroserviceMethodId = new Guid("dd000000-0000-0000-0000-000000000002"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            HttpMethod = "GET",
                            MicroserviceId = new Guid("cc000000-0000-0000-0000-000000000002"),
                            MicroserviceMethodDelete = false,
                            MicroserviceMethodName = "SearchProducts",
                            MicroserviceMethodUrl = "/api/products/search",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroserviceRegister", b =>
                {
                    b.Property<Guid>("MicroserviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_microservice_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_create_at");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_delete_at");

                    b.Property<bool?>("MicroserviceActive")
                        .HasColumnType("boolean")
                        .HasColumnName("fastserver_microservice_active");

                    b.Property<bool?>("MicroserviceCoreConnection")
                        .HasColumnType("boolean")
                        .HasColumnName("fastserver_microservice_core_connection");

                    b.Property<bool?>("MicroserviceDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("fastserver_microservice_deleted");

                    b.Property<string>("MicroserviceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fastserver_microservice_name");

                    b.Property<Guid?>("MicroserviceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_microservice_type_id");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_modify_at");

                    b.Property<string>("SoapBase")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("fastserver_soap_base");

                    b.HasKey("MicroserviceId");

                    b.HasIndex("MicroserviceName")
                        .HasDatabaseName("IX_FastServer_Microservice_Register_Name");

                    b.HasIndex("MicroserviceTypeId")
                        .HasDatabaseName("IX_FastServer_Microservice_Register_TypeId");

                    b.ToTable("FastServer_Microservice_Register", (string)null);

                    b.HasData(
                        new
                        {
                            MicroserviceId = new Guid("cc000000-0000-0000-0000-000000000001"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroserviceActive = true,
                            MicroserviceCoreConnection = true,
                            MicroserviceDeleted = false,
                            MicroserviceName = "AuthService",
                            MicroserviceTypeId = new Guid("aa000000-0000-0000-0000-000000000001"),
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MicroserviceId = new Guid("cc000000-0000-0000-0000-000000000002"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroserviceActive = true,
                            MicroserviceCoreConnection = true,
                            MicroserviceDeleted = false,
                            MicroserviceName = "ProductService",
                            MicroserviceTypeId = new Guid("aa000000-0000-0000-0000-000000000002"),
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            SoapBase = "https://core.davivienda.hn/soap/products"
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroservicesCluster", b =>
                {
                    b.Property<Guid>("MicroservicesClusterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_microservices_cluster_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_create_at");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_delete_at");

                    b.Property<bool?>("MicroservicesClusterActive")
                        .HasColumnType("boolean")
                        .HasColumnName("fastserver_microservices_cluster_active");

                    b.Property<bool?>("MicroservicesClusterDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("fastserver_microservices_cluster_deleted");

                    b.Property<string>("MicroservicesClusterName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fastserver_microservices_cluster_name");

                    b.Property<string>("MicroservicesClusterProtocol")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("fastserver_microservices_cluster_protocol");

                    b.Property<string>("MicroservicesClusterServerIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fastserver_microservices_cluster_server_ip");

                    b.Property<string>("MicroservicesClusterServerName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fastserver_microservices_cluster_server_name");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_modify_at");

                    b.HasKey("MicroservicesClusterId");

                    b.HasIndex("MicroservicesClusterName")
                        .HasDatabaseName("IX_FastServer_Microservices_Cluster_Name");

                    b.ToTable("FastServer_Microservices_Cluster", (string)null);

                    b.HasData(
                        new
                        {
                            MicroservicesClusterId = new Guid("bb000000-0000-0000-0000-000000000001"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroservicesClusterActive = true,
                            MicroservicesClusterDeleted = false,
                            MicroservicesClusterName = "Production Cluster",
                            MicroservicesClusterProtocol = "HTTPS",
                            MicroservicesClusterServerIp = "10.0.1.100",
                            MicroservicesClusterServerName = "prod-cluster-01",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MicroservicesClusterId = new Guid("bb000000-0000-0000-0000-000000000002"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroservicesClusterActive = true,
                            MicroservicesClusterDeleted = false,
                            MicroservicesClusterName = "Development Cluster",
                            MicroservicesClusterProtocol = "HTTP",
                            MicroservicesClusterServerIp = "10.0.2.100",
                            MicroservicesClusterServerName = "dev-cluster-01",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroservicesRegisterType", b =>
                {
                    b.Property<Guid>("MicroservicesRegisterTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_microservices_register_type_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_create_at");

                    b.Property<string>("MicroservicesRegisterTypeDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fastserver_microservices_register_type_description");

                    b.Property<string>("MicroservicesRegisterTypeName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fastserver_microservices_register_type_name");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_modify_at");

                    b.HasKey("MicroservicesRegisterTypeId");

                    b.HasIndex("MicroservicesRegisterTypeName")
                        .HasDatabaseName("IX_FastServer_Microservices_RegisterType_Name");

                    b.ToTable("FastServer_Microservices_RegisterType", (string)null);

                    b.HasData(
                        new
                        {
                            MicroservicesRegisterTypeId = new Guid("aa000000-0000-0000-0000-000000000001"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroservicesRegisterTypeDescription = "Microservicio basado en API REST",
                            MicroservicesRegisterTypeName = "REST",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MicroservicesRegisterTypeId = new Guid("aa000000-0000-0000-0000-000000000002"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroservicesRegisterTypeDescription = "Microservicio basado en SOAP/XML",
                            MicroservicesRegisterTypeName = "SOAP",
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.Nodo", b =>
                {
                    b.Property<Guid>("NodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_nodo_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_create_at");

                    b.Property<Guid>("MicroserviceMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_microservice_method_id");

                    b.Property<Guid>("MicroservicesClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_microservices_cluster_id");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_modify_at");

                    b.HasKey("NodoId");

                    b.HasIndex("MicroservicesClusterId")
                        .HasDatabaseName("IX_FastServer_Nodo_ClusterId");

                    b.HasIndex("MicroserviceMethodId", "MicroservicesClusterId")
                        .IsUnique()
                        .HasDatabaseName("UX_FastServer_Nodo_Method_Cluster");

                    b.ToTable("FastServer_Nodo", (string)null);

                    b.HasData(
                        new
                        {
                            NodoId = new Guid("22000000-0000-0000-0000-000000000001"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroserviceMethodId = new Guid("dd000000-0000-0000-0000-000000000001"),
                            MicroservicesClusterId = new Guid("bb000000-0000-0000-0000-000000000001"),
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            NodoId = new Guid("22000000-0000-0000-0000-000000000002"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            MicroserviceMethodId = new Guid("dd000000-0000-0000-0000-000000000002"),
                            MicroservicesClusterId = new Guid("bb000000-0000-0000-0000-000000000001"),
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("fastserver_user_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_create_at");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("fastserver_email_confirmed");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_last_login");

                    b.Property<DateTime?>("ModifyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_modify_at");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_password_changed_at");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fastserver_password_hash");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fastserver_refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fastserver_refresh_token_expiry_time");

                    b.Property<bool?>("UserActive")
                        .HasColumnType("boolean")
                        .HasColumnName("fastserver_user_active");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fastserver_user_email");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fastserver_user_name");

                    b.Property<string>("UserPeoplesoft")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fastserver_user_peoplesoft");

                    b.HasKey("UserId");

                    b.HasIndex("UserEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_FastServer_User_Email");

                    b.HasIndex("UserPeoplesoft")
                        .HasDatabaseName("IX_FastServer_User_Peoplesoft");

                    b.ToTable("FastServer_User", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
                            UserActive = true,
                            UserEmail = "admin@fastserver.com",
                            UserName = "Admin User",
                            UserPeoplesoft = "PS001"
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreateAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = true,
                            ModifyAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$VRjNO0ZRwK7x1Z.XfJcKAOKs7ggzwhPB3QVpLp2PF3cxyMq7R5rHu",
                            UserActive = true,
                            UserEmail = "developer@fastserver.com",
                            UserName = "Developer User",
                            UserPeoplesoft = "PS002"
                        });
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.ActivityLog", b =>
                {
                    b.HasOne("FastServer.Domain.Entities.Microservices.EventType", "EventType")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FastServer.Domain.Entities.Microservices.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EventType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroserviceCoreConnector", b =>
                {
                    b.HasOne("FastServer.Domain.Entities.Microservices.CoreConnectorCredential", "CoreConnectorCredential")
                        .WithMany("MicroserviceCoreConnectors")
                        .HasForeignKey("CoreConnectorCredentialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FastServer.Domain.Entities.Microservices.MicroserviceRegister", "MicroserviceRegister")
                        .WithMany("MicroserviceCoreConnectors")
                        .HasForeignKey("MicroserviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CoreConnectorCredential");

                    b.Navigation("MicroserviceRegister");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroserviceMethod", b =>
                {
                    b.HasOne("FastServer.Domain.Entities.Microservices.MicroserviceRegister", "MicroserviceRegister")
                        .WithMany("MicroserviceMethods")
                        .HasForeignKey("MicroserviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MicroserviceRegister");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroserviceRegister", b =>
                {
                    b.HasOne("FastServer.Domain.Entities.Microservices.MicroservicesRegisterType", "MicroserviceType")
                        .WithMany("MicroserviceRegisters")
                        .HasForeignKey("MicroserviceTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MicroserviceType");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.Nodo", b =>
                {
                    b.HasOne("FastServer.Domain.Entities.Microservices.MicroserviceMethod", "MicroserviceMethod")
                        .WithMany("Nodos")
                        .HasForeignKey("MicroserviceMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastServer.Domain.Entities.Microservices.MicroservicesCluster", "MicroservicesCluster")
                        .WithMany("Nodos")
                        .HasForeignKey("MicroservicesClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MicroserviceMethod");

                    b.Navigation("MicroservicesCluster");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.CoreConnectorCredential", b =>
                {
                    b.Navigation("MicroserviceCoreConnectors");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.EventType", b =>
                {
                    b.Navigation("ActivityLogs");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroserviceMethod", b =>
                {
                    b.Navigation("Nodos");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroserviceRegister", b =>
                {
                    b.Navigation("MicroserviceCoreConnectors");

                    b.Navigation("MicroserviceMethods");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroservicesCluster", b =>
                {
                    b.Navigation("Nodos");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.MicroservicesRegisterType", b =>
                {
                    b.Navigation("MicroserviceRegisters");
                });

            modelBuilder.Entity("FastServer.Domain.Entities.Microservices.User", b =>
                {
                    b.Navigation("ActivityLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
